#!/bin/bash

###############################################################################
#
#  This script will take a checklist as input and then prepend it with a header
#  required for it to work as a GitHub issue template.
#
###############################################################################

if [[ $# -ne 1 ]]; then
  echo "Usage:  github-ify filename, where filename is a path to a checklist."
  exit 1
fi

filename="$1"
contents=$(<${filename})
title="$(awk 'NR == 1 {print}' ${filename})"
title="${title:2}"
description="$(awk 'NR == 2 {print}' ${filename})"
if [[ "${description}" == "" ]]; then
  description="''"
fi
header="---
name: ${title}
about: ${description}
title: ${title}
lables: ''
assignees: ''

---
"
echo "${header}${contents}" > ${filename}
